-- MySQL Script generated by MySQL Workbench
-- Thu 18 Apr 2019 03:48:48 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 4cesNet-DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 4cesNet-DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4cesNet-DB` DEFAULT CHARACTER SET utf8 ;
USE `4cesNet-DB` ;

-- -----------------------------------------------------
-- Table `4cesNet-DB`.`contributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`contributors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`projects` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`commits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`commits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT(10) UNSIGNED NOT NULL,
  `contributor_id` INT(10) UNSIGNED NOT NULL,
  `committer_id` INT(10) UNSIGNED NOT NULL,
  `hash` VARCHAR(45) NULL DEFAULT NULL,
  `commit_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_id_idx` (`project_id` ASC),
  INDEX `fk_commits_developer_id_idx` (`contributor_id` ASC),
  CONSTRAINT `fk_commits_developer_id`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commits_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `4cesNet-DB`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`merge_scenarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`merge_scenarios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT(10) UNSIGNED NOT NULL,
  `commit_base` INT(10) UNSIGNED NOT NULL,
  `commit_merge` INT(10) UNSIGNED NOT NULL,
  `has_conflict` TINYINT(1) NOT NULL,
  `merge_commit_date` DATETIME NOT NULL,
  `base_commit_date` DATETIME NOT NULL,
  `merge_commit_hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commit_base_idx` (`commit_base` ASC),
  INDEX `fk_ms_commit_merge_idx` (`commit_merge` ASC),
  INDEX `fk_ms_project_id_idx` (`project_id` ASC),
  CONSTRAINT `fk_ms_commit_base`
    FOREIGN KEY (`commit_base`)
    REFERENCES `4cesNet-DB`.`commits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_commit_merge`
    FOREIGN KEY (`commit_merge`)
    REFERENCES `4cesNet-DB`.`commits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `4cesNet-DB`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`files` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `filepath` VARCHAR(300) NULL DEFAULT NULL,
  `merge_scenarios_id` INT(10) UNSIGNED NOT NULL,
  `has_conflict` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_merge_scenario_id_idx` (`merge_scenarios_id` ASC),
  CONSTRAINT `fk_merge_scenario_id`
    FOREIGN KEY (`merge_scenarios_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`chunks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`chunks` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_id` INT(10) UNSIGNED NOT NULL,
  `begin_line` INT(10) UNSIGNED NOT NULL,
  `end_line` INT(10) UNSIGNED NOT NULL,
  `has_conflict` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_id_idx` (`file_id` ASC),
  CONSTRAINT `fk_file_id`
    FOREIGN KEY (`file_id`)
    REFERENCES `4cesNet-DB`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`chunk_commits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`chunk_commits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chunk_id` INT(10) UNSIGNED NOT NULL,
  `commit_id` INT(10) UNSIGNED NOT NULL,
  `side` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chunk_commits_commit_id_idx` (`commit_id` ASC),
  INDEX `fk_chunk_commits_chunk_id_idx` (`chunk_id` ASC),
  CONSTRAINT `fk_chunk_commits_chunk_id`
    FOREIGN KEY (`chunk_id`)
    REFERENCES `4cesNet-DB`.`chunks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chunk_commits_commit_id`
    FOREIGN KEY (`commit_id`)
    REFERENCES `4cesNet-DB`.`commits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`chunk_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`chunk_metrics` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chunk_id` INT(10) UNSIGNED NOT NULL,
  `number_commits` INT(10) UNSIGNED NOT NULL,
  `number_left_commits` INT(10) UNSIGNED NOT NULL,
  `number_right_commits` INT(10) UNSIGNED NOT NULL,
  `number_developers` INT(10) UNSIGNED NOT NULL,
  `number_left_dev` INT(10) UNSIGNED NOT NULL,
  `number_right_dev` INT(10) UNSIGNED NOT NULL,
  `number_both_side_dev` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chunk_metrics_to_chunks_idx` (`chunk_id` ASC),
  CONSTRAINT `fk_chunk_metrics_to_chunks`
    FOREIGN KEY (`chunk_id`)
    REFERENCES `4cesNet-DB`.`chunks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`networks` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_scenarios_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_networks_merge_scenario_id_idx` (`merge_scenarios_id` ASC),
  CONSTRAINT `fk_networks_merge_scenario_id`
    FOREIGN KEY (`merge_scenarios_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`edges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`edges` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `network_id` INT(10) UNSIGNED NOT NULL,
  `dev_a` INT(10) UNSIGNED NOT NULL,
  `dev_b` INT(10) UNSIGNED NOT NULL,
  `type` INT(10) UNSIGNED NOT NULL,
  `weight` INT(10) UNSIGNED NOT NULL,
  `side` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_edge_dev_b` (`dev_b` ASC),
  INDEX `fk_dev_b_idx` (`dev_a` ASC),
  INDEX `fk_edge_network_id_idx` (`network_id` ASC),
  CONSTRAINT `fk_edge_dev_a`
    FOREIGN KEY (`dev_a`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_edge_dev_b`
    FOREIGN KEY (`dev_b`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_edge_network_id`
    FOREIGN KEY (`network_id`)
    REFERENCES `4cesNet-DB`.`networks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`email` (
  `contributors_id` INT(10) UNSIGNED NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  INDEX `fk_contributor_id_idx` (`contributors_id` ASC),
  CONSTRAINT `fk_email_contributor_id`
    FOREIGN KEY (`contributors_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`issues` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT(10) UNSIGNED NOT NULL,
  `gh_issue_id` INT(10) UNSIGNED NOT NULL,
  `open_date` DATETIME NOT NULL,
  `close_date` DATETIME NULL DEFAULT NULL,
  `is_pull_request` TINYINT(1) NOT NULL,
  `is_closed` TINYINT(1) NOT NULL,
  `pull_commit_hash` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_issue_project_id_idx` (`project_id` ASC),
  CONSTRAINT `fk_issue_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `4cesNet-DB`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`events` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `issue_id` INT(10) UNSIGNED NOT NULL,
  `contributor_id` INT(10) UNSIGNED NOT NULL,
  `is_commentary` TINYINT(1) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_developer_id_idx` (`contributor_id` ASC),
  INDEX `fk_events_issue_id_idx` (`issue_id` ASC),
  CONSTRAINT `fk_events_developer_id`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_issue_id`
    FOREIGN KEY (`issue_id`)
    REFERENCES `4cesNet-DB`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`file_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`file_metrics` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_id` INT(10) UNSIGNED NOT NULL,
  `number_chunks` INT(10) UNSIGNED NOT NULL,
  `number_conflicted_chunks` INT(10) UNSIGNED NOT NULL,
  `number_left_chunks` INT(10) UNSIGNED NOT NULL,
  `number_right_chunks` INT(10) UNSIGNED NOT NULL,
  `number_commits` INT(10) UNSIGNED NOT NULL,
  `number_left_commits` INT(10) UNSIGNED NOT NULL,
  `number_right_commits` INT(10) UNSIGNED NOT NULL,
  `number_developers` INT(10) UNSIGNED NOT NULL,
  `number_left_dev` INT(10) UNSIGNED NOT NULL,
  `number_right_dev` INT(10) UNSIGNED NOT NULL,
  `number_both_side_dev` INT(10) UNSIGNED NOT NULL,
  `loc` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_metrics_to_files_idx` (`file_id` ASC),
  CONSTRAINT `fk_file_metrics_to_files`
    FOREIGN KEY (`file_id`)
    REFERENCES `4cesNet-DB`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`issue_commits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`issue_commits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `commit_id` INT(10) UNSIGNED NOT NULL,
  `issue_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_related_commits_1_idx` (`commit_id` ASC),
  INDEX `fk_rc_issue_id_idx` (`issue_id` ASC),
  CONSTRAINT `fk_rc_commit_id`
    FOREIGN KEY (`commit_id`)
    REFERENCES `4cesNet-DB`.`commits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rc_issue_id`
    FOREIGN KEY (`issue_id`)
    REFERENCES `4cesNet-DB`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`labels` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`ms_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`ms_metrics` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_scenario_id` INT(10) UNSIGNED NOT NULL,
  `number_of_files` INT(10) UNSIGNED NOT NULL,
  `number_conflicted_files` INT(10) UNSIGNED NOT NULL,
  `number_left_files` INT(10) UNSIGNED NOT NULL,
  `number_right_files` INT(10) UNSIGNED NOT NULL,
  `number_both_side_files` INT(10) UNSIGNED NOT NULL,
  `number_chunks` INT(10) UNSIGNED NOT NULL,
  `number_conflicted_chunks` INT(10) UNSIGNED NOT NULL,
  `number_left_chunks` INT(10) UNSIGNED NOT NULL,
  `number_right_chunks` INT(10) UNSIGNED NOT NULL,
  `number_commits` INT(10) UNSIGNED NOT NULL,
  `number_left_commits` INT(10) UNSIGNED NOT NULL,
  `number_right_commits` INT(10) UNSIGNED NOT NULL,
  `number_developers` INT(10) UNSIGNED NOT NULL,
  `number_left_dev` INT(10) UNSIGNED NOT NULL,
  `number_right_dev` INT(10) UNSIGNED NOT NULL,
  `number_both_side_dev` INT(10) UNSIGNED NOT NULL,
  `code_churn` INT(10) UNSIGNED NOT NULL,
  `conflict_code_churn` INT(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ms_metrics_to_merge_scenarios_idx` (`merge_scenario_id` ASC),
  CONSTRAINT `fk_ms_metrics_to_merge_scenarios`
    FOREIGN KEY (`merge_scenario_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`net_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`net_metrics` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `network_id` INT(10) UNSIGNED NOT NULL,
  `coverage_file_chunk` INT(10) UNSIGNED NOT NULL,
  `coverage_ms_file` INT(10) UNSIGNED NOT NULL,
  `coverage_chunk_comprehensive` INT(10) UNSIGNED NOT NULL,
  `coverage_chunk_precise` INT(10) UNSIGNED NOT NULL,
  `coverage_chunk_artifact` INT(10) UNSIGNED NOT NULL,
  `coverage_file_comprehensive` INT(10) UNSIGNED NOT NULL,
  `coverage_file_precise` INT(10) UNSIGNED NOT NULL,
  `coverage_file_artifact` INT(10) UNSIGNED NOT NULL,
  `coverage_ms_comprehensive` INT(10) UNSIGNED NOT NULL,
  `coverage_ms_precise` INT(10) UNSIGNED NOT NULL,
  `coverage_ms_artifact` INT(10) UNSIGNED NOT NULL,
  `coverage_comprehensive_chunk` INT(10) UNSIGNED NOT NULL,
  `coverage_precise_chunk` INT(10) UNSIGNED NOT NULL,
  `coverage_artifact_chunk` INT(10) UNSIGNED NOT NULL,
  `coverage_comprehensive_file` INT(10) UNSIGNED NOT NULL,
  `coverage_precise_file` INT(10) UNSIGNED NOT NULL,
  `coverage_artifact_file` INT(10) UNSIGNED NOT NULL,
  `coverage_comprehensive_ms` INT(10) UNSIGNED NOT NULL,
  `coverage_precise_ms` INT(10) UNSIGNED NOT NULL,
  `coverage_artifact_ms` INT(10) UNSIGNED NOT NULL,
  `number_comprehensive_edges` INT(10) UNSIGNED NOT NULL,
  `number_precise_edges` INT(10) UNSIGNED NOT NULL,
  `number_artifact_edges` INT(10) UNSIGNED NOT NULL,
  `number_chunk_edges` INT(10) UNSIGNED NOT NULL,
  `number_file_edges` INT(10) UNSIGNED NOT NULL,
  `number_ms_edges` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_net_metrics_to_networks_idx` (`network_id` ASC),
  CONSTRAINT `fk_net_metrics_to_networks`
    FOREIGN KEY (`network_id`)
    REFERENCES `4cesNet-DB`.`networks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`project_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`project_metrics` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT(10) UNSIGNED NOT NULL,
  `loc` INT(10) UNSIGNED NOT NULL,
  `ms_computed` INT(10) UNSIGNED NOT NULL,
  `ms_ignored` INT(10) UNSIGNED NOT NULL,
  `ms_conflicted` INT(10) UNSIGNED NOT NULL,
  `number_of_files` INT(10) UNSIGNED NOT NULL,
  `number_of_chunks` INT(10) UNSIGNED NOT NULL,
  `number_of_commits` INT(10) UNSIGNED NOT NULL,
  `number_of_developers` INT(10) UNSIGNED NOT NULL,
  `num_of_distinct_files` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_metrics_to_projects_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_metrics_to_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `4cesNet-DB`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`related_issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`related_issues` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `issue_id` INT(10) UNSIGNED NOT NULL,
  `related_issue_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rl_issue_id_idx` (`issue_id` ASC),
  INDEX `fk_rl_related_issue_id_idx` (`related_issue_id` ASC),
  CONSTRAINT `fk_ri_issue_id`
    FOREIGN KEY (`issue_id`)
    REFERENCES `4cesNet-DB`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ri_related_issue_id`
    FOREIGN KEY (`related_issue_id`)
    REFERENCES `4cesNet-DB`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`related_labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`related_labels` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `issue_id` INT(10) UNSIGNED NOT NULL,
  `label_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rl_issue_id_idx` (`issue_id` ASC),
  INDEX `fk_rl_labels_id_idx` (`label_id` ASC),
  CONSTRAINT `fk_rl_issue_id`
    FOREIGN KEY (`issue_id`)
    REFERENCES `4cesNet-DB`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rl_labels_id`
    FOREIGN KEY (`label_id`)
    REFERENCES `4cesNet-DB`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`devs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`devs` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_scenario_id` INT(10) UNSIGNED NOT NULL,
  `contributor_id` INT(10) UNSIGNED NOT NULL,
  `number_files_left` INT(10) UNSIGNED NOT NULL,
  `number_files_right` INT(10) UNSIGNED NOT NULL,
  `number_chunks_left` INT(10) UNSIGNED NOT NULL,
  `number_chunks_right` INT(10) UNSIGNED NOT NULL,
  `number_changed_lines_left` INT(10) UNSIGNED NOT NULL,
  `number_changed_lines_right` INT(10) UNSIGNED NOT NULL,
  `number_commits_left` INT(10) UNSIGNED NOT NULL,
  `number_commits_right` INT(10) UNSIGNED NOT NULL,
  `last_change_left` TINYINT(1) NOT NULL,
  `last_change_right` TINYINT(1) NOT NULL,
  `is_integrator` TINYINT(1) NOT NULL,
  `contribute_conflict` TINYINT(1) NOT NULL,
  `is_core_dev` TINYINT(1) NOT NULL,
  `is_left_branch_leader` TINYINT(1) NOT NULL,
  `is_right_branch_leader` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_devs_contributors_idx` (`contributor_id` ASC),
  INDEX `fk_devs_merge_scenarios_idx` (`merge_scenario_id` ASC),
  CONSTRAINT `fk_devs_contributors`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devs_merge_scenarios`
    FOREIGN KEY (`merge_scenario_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`committers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`committers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_scenario_id` INT(10) UNSIGNED NOT NULL,
  `contributor_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_committer_merge_scenario_idx` (`merge_scenario_id` ASC),
  INDEX `fk_committer_contributor_idx` (`contributor_id` ASC),
  CONSTRAINT `fk_committer_merge_scenario`
    FOREIGN KEY (`merge_scenario_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_committer_contributor`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`communicators_devs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`communicators_devs` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_scenario_id` INT(10) UNSIGNED NOT NULL,
  `contributor_id` INT(10) UNSIGNED NOT NULL,
  `approach` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_communicator_contributor_idx` (`contributor_id` ASC),
  INDEX `fk_communicator_merge_scenario_idx` (`merge_scenario_id` ASC),
  CONSTRAINT `fk_communicator_devs_contributor`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_communicator_devs_merge_scenario`
    FOREIGN KEY (`merge_scenario_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`communicators_conts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`communicators_conts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_scenario_id` INT(10) UNSIGNED NOT NULL,
  `contributor_id` INT(10) UNSIGNED NOT NULL,
  `approach` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_communicator_contributor_idx` (`contributor_id` ASC),
  INDEX `fk_communicator_merge_scenario_idx` (`merge_scenario_id` ASC),
  CONSTRAINT `fk_communicator_conts_contributor`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_communicator_conts_merge_scenario`
    FOREIGN KEY (`merge_scenario_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`integrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`integrators` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_scenario_id` INT(10) UNSIGNED NOT NULL,
  `contributor_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commiter_merge_scenario_idx` (`merge_scenario_id` ASC),
  INDEX `fk_commiter_contributor_idx` (`contributor_id` ASC),
  CONSTRAINT `fk_integrator_merge_scenario`
    FOREIGN KEY (`merge_scenario_id`)
    REFERENCES `4cesNet-DB`.`merge_scenarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_integrators_contributor`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `4cesNet-DB`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`merge_conflict_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`merge_conflict_info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chunk_id` INT(10) UNSIGNED NOT NULL,
  `left_commit_id` INT(10) UNSIGNED NOT NULL,
  `right_commit_id` INT(10) UNSIGNED NOT NULL,
  `left_code` LONGTEXT NOT NULL,
  `right_code` LONGTEXT NOT NULL,
  `merged_code` LONGTEXT NOT NULL,
  `left_merge_time_diff` BIGINT(10) NOT NULL,
  `right_merge_time_diff` BIGINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_merge_conflict_info_chunk_id_idx` (`chunk_id` ASC),
  INDEX `fk_merge_conflict_info_left_commit_id_idx` (`left_commit_id` ASC),
  INDEX `fk_merge_conflict_info_right_commit_id_idx` (`right_commit_id` ASC),
  CONSTRAINT `fk_merge_conflict_info_chunk_id`
    FOREIGN KEY (`chunk_id`)
    REFERENCES `4cesNet-DB`.`chunks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_merge_conflict_info_left_commit_id`
    FOREIGN KEY (`left_commit_id`)
    REFERENCES `4cesNet-DB`.`commits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_merge_conflict_info_right_commit_id`
    FOREIGN KEY (`right_commit_id`)
    REFERENCES `4cesNet-DB`.`commits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4cesNet-DB`.`merge_conflict_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4cesNet-DB`.`merge_conflict_metrics` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `merge_conflict_info_id` INT(10) UNSIGNED NOT NULL,
  `change_type` VARCHAR(20) NOT NULL,
  `loc` INT(10) UNSIGNED NOT NULL,
  `left_loc` INT(10) UNSIGNED NOT NULL,
  `right_loc` INT(10) UNSIGNED NOT NULL,
  `cyclomatic_complexity` INT(10) UNSIGNED NOT NULL,
  `left_cyclomatic_complexity` INT(10) UNSIGNED NOT NULL,
  `right_cyclomatic_complexity` INT(10) UNSIGNED NOT NULL,
  `dev_has_knowledge` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_merge_conflict_metrics_merge_conflict_info_idx` (`merge_conflict_info_id` ASC),
  CONSTRAINT `fk_merge_conflict_metrics_merge_conflict_info`
    FOREIGN KEY (`merge_conflict_info_id`)
    REFERENCES `4cesNet-DB`.`merge_conflict_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
